# Command to run this playbook: ansible-playbook -i inventory.cfg nginx_install.yml -b [ -b tells ansible to become root on the remote server using sudo ]

---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
